Add redis db backend
tuna/tunasync pull request #141
Opened 2020-10-13 11:35 UTC by jiegec

2020-10-13 12:43 UTC, bigeagle commented
LGTM

2020-10-13 12:47 UTC, shankerwangmiao commented
I wonder if we can adopt a database abstraction layer to reduce repeated code?

2020-10-13 12:48 UTC, jiegec commented
> I wonder if we can adopt a database abstraction layer to reduce repeated code?

Yes, we can abstract one more level out here.

2020-10-14 12:33 UTC, z4yx requested changes

2020-10-14 12:33 UTC, z4yx commented on manager/server.go
> +			err = fmt.Errorf("failed to get job %s of worker %s: %s",
这儿给 err 赋值后并没有用到吧。我想作者原意应该是打log，但是误用了函数。

2020-10-14 23:33 UTC, jiegec commented on manager/server.go
> +			err = fmt.Errorf("failed to get job %s of worker %s: %s",
改成 logger.Errorf 了

2020-10-15 13:25 UTC, z4yx approved these changes

2020-10-15 13:25 UTC, merged